add_color_bar: 'True'
add_contour_overlay: 'True'
alpha: 0.05

caption_align: 0.0
caption_col: '#333333'
caption_offset: 3.0
caption_size: 0.8
caption_weight: 1
cex: 1
circular_block_bootstrap: 'True'
cl_step: 0.05
color_palette: green_red
colors:
- '#000000'

contour_diff: 'False'
contour_intervals: 10
create_html: 'False'
dump_points_1: 'False'
equalize_by_indep: 'False'
event_equal: 'False'
fcst_var_val_1: {}

indy_label: []
indy_vals: []

indy_var: ''
list_stat_1: []
legend_box: o
legend_inset:
  x: 0.0
  y: -0.25
legend_ncol: 3
legend_size: 0.8
line_type: None
mar:
- 8.0
- 4.0
- 5.0
- 4.0
method: bca
mgp:
- 1.0
- 1.0
- 0.0
num_iterations: 1
num_threads: -1
plot_caption: ''

plot_disp:
- 'True'
plot_filename: /tmp/contour.png
plot_height: 8.5
plot_res: 72
plot_stat: median
plot_type: png16m
plot_units: in
plot_width: 11.0
random_seed: null
reverse_x: 'False'
reverse_y: 'False'
series_line_style:
- '-'
series_line_width:
- 1
series_order:
- 1

series_val_1: {}

stat_input: ../../../test/contour/contour.data
title: test title
title_align: 0.5
title_offset: -2
title_size: 1.4
title_weight: 2.0
user_legend: []

xaxis: test x_label
xlab_align: 0.5
xlab_offset: 2
xlab_size: 1
xlab_weight: 1
xlim: []
xtlab_decim: 0
xtlab_horiz: 0.5
xtlab_orient: 1
xtlab_perp: -0.75
xtlab_size: 1

yaxis_1: test y_label
ylab_align: 0.5
ylab_offset: -2
ylab_size: 1
ylab_weight: 1
ylim: []
ytlab_horiz: 0.5
ytlab_orient: 1
ytlab_perp: 0.5
ytlab_size: 1
