caption_align: 0.0
caption_col: '#333333'
caption_offset: 3.0
caption_size: 0.8
caption_weight: 1
cex: 1
colors: []


create_html: 'False'
dump_points_1: 'False'
ensss_pts: -1
ensss_pts_disp: 'False'
event_equal: 'False'
fcst_var_val_1: {}
fixed_vars_vals_input: {}
grid_col: '#cccccc'
grid_lty: 3
grid_lwd: 1
grid_on: 'True'
grid_x: listX
indy_label: []
indy_vals: []
indy_var: ''
legend_box: o
legend_inset:
  x: 0.0
  y: -0.25
legend_ncol: 3
legend_size: 0.8
line_type: None
list_stat_1: []
list_stat_2: []
list_static_val: {}
mar:
- 8
- 4
- 5
- 4
mgp:
- 1
- 1
- 0
plot_caption: ''

plot_disp: []

plot_filename: ./ens_ss.png
plot_height: 8.5
plot_res: 72
plot_type: png16m
plot_units: in
plot_width: 11.0
series_line_style: []
series_line_width: []
series_order: []
series_symbols: []
series_type: []
series_val_1: {}
stat_input: ./input.data
title: test title
title_align: 0.5
title_offset: -2
title_size: 1.4
title_weight: 2.0
user_legend: []

xaxis: test x_label
xaxis_reverse: 'False'
xlab_align: 0.5
xlab_offset: 2
xlab_size: 1
xlab_weight: 1
xlim: []
xtlab_decim: 0
xtlab_horiz: 0.5
xtlab_orient: 1
xtlab_perp: -0.75
xtlab_size: 1

yaxis_1: test y_label
yaxis_2: ''
ylab_align: 0.5
ylab_offset: -2
ylab_size: 1
ylab_weight: 1
ylim: []
ytlab_horiz: 0.5
ytlab_orient: 1
ytlab_perp: 0.5
ytlab_size: 1
y2lab_align: 0.5
y2lab_offset: 1
y2lab_size: 1
y2lab_weight: 1
y2lim: []
y2tlab_horiz: 0.5
y2tlab_orient: 1
y2tlab_perp: 1
y2tlab_size: 1.0