wind_rose: True
plot_filename: mpr_plots.png
wind_rose_breaks:
  - 0.0
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
wind_rose_angle: 30
wind_rose_marker_colors:
  - 'rgb(95,78,160)'
  - 'rgb(78,176,170)'
  - 'rgb(192,228,160)'
  - 'rgb(255,255,194)'
  - 'rgb(253,193,115)'
  - 'rgb(236,94,74)'
  - 'rgb(159,11,68)'
angularaxis_tickvals:
  - 0
  - 90
  - 180
  - 270
angularaxis_ticktext:
  - 'N'
  - 'E'
  - 'S'
  - 'W'
log_filename: stdout
log_level: error 
width: 1200
height: 7500
marker_color: 'rgb(194,189,251)'
show_in_browser: False

# Not used in this plot, but if incorporating into METviewer
plot_units: in
xlab_align: 0.5
xlab_offset: 2
xlab_size: 1
xlab_weight: 1
xlim: []
xtlab_decim: 0
xtlab_horiz: 0.5
xtlab_orient: 1
xtlab_perp: -0.75
xtlab_size: 1
y2lab_align: 0.5
y2lab_offset: 1
y2lab_size: 1
y2lab_weight: 1
y2lim: []
y2tlab_horiz: 0.5
y2tlab_orient: 1
y2tlab_perp: 1
y2tlab_size: 1.0
yaxis_1: test y_label
yaxis_2: ''
ylab_align: 0.5
ylab_offset: -2
ylab_size: 1
ylab_weight: 1
ylim: []
ytlab_horiz: 0.5
ytlab_orient: 1
ytlab_perp: 0.5
ytlab_size: 1
caption_align: 0.0
caption_col: '#333333'
caption_offset: 3.0
caption_size: 0.8
caption_weight: 1
title_align: 0.5
title_offset: -2
title_size: 1.4
title_weight: 2.0
legend_box: o
legend_inset:
  x: 0.0
  y: -0.25
legend_ncol: 1
legend_size: 0.8