alpha: 0.05
colors:
  - '#696969'
  - '#0000FF'
  - '#008000'
  - '#000000'
  - '#ff0000'
  - '#800080'
  - '#FFA500'
create_html: 'False'
derived_series_1: []
fixed_vars_vals_input:
  BASIN:
    BASIN_0:
    - AL

grid_col: '#cccccc'
grid_lty: 3
grid_lwd: 1
grid_on: 'False'
grid_x: listX

indy_vals: []

indy_label: []

indy_var: 'LEAD'
legend_box: o
legend_inset:
  x: 0.0
  y: -0.25
legend_ncol: 3
legend_size: 0.8
line_type: None

list_stat_1: []
log_filename: /tmp/tcmpr.log
log_level: 'DEBUG'

mar:
  l: 0 #left margin
  r: 0 #right margin
  b: 105 #bottom margin
  t: 120 #top margin
mgp:
- 1
- 1
- 0
plot_caption: ''
plot_disp: []

plot_height: 8.5
plot_res: 72
plot_stat: median
plot_type: png16m
plot_units: in
plot_width: 11.0
series_order: []
series_val_1: {}
series_ci: []
series_line_width:
- 1
- 1
- 1
series_line_style:
  - '-'
  - '-'
  - '-'
series_symbols:
- 'circle-open'
- 'circle-open'
- 'circle-open'

series_symbols_size:
  - 7
  - 7
  - 7


show_nstats: 'True'

tcst_dir:
tcst_files: []

title:
title_align: 0.5
title_offset: -2.0833
title_size: 1.4
title_weight: 2.0
user_legend: []
x2lab_align: 0.5
x2lab_offset: -0.5
x2lab_size: 0.8
x2lab_weight: 1
x2tlab_horiz: 0.5
x2tlab_orient: 1
x2tlab_perp: 1
x2tlab_size: 0.8
xaxis: 'Lead Time(h)'
xaxis_reverse: 'False'
xlab_align: 0.5
xlab_offset: 2
xlab_size: 1
xlab_weight: 1
xlim: []
xtlab_decim: 0
xtlab_horiz: 0.5
xtlab_orient: 1
xtlab_perp: -0.75
xtlab_size: 1

yaxis_1:
ylab_align: 0.5
ylab_offset: 15
ylab_size: 1
ylab_weight: 1
ylim: []
ytlab_horiz: 0.5
ytlab_orient: 1
ytlab_perp: 0.5
ytlab_size: 1

box_notch: True
box_outline: True
box_avg: True

caption_size: 0.8
caption_offset: 3
caption_weight: 1
caption_align: 0
caption_col: '#333333'
n_min: 11
plot_list: [] # boxplot, point, mean, median, relperf, rank, scatter ,skill_mn, skill_md
rp_diff:
  - '>=100'
hfip_bsln: no
footnote_flag: 'False'
event_equal: 'False'
skill_ref: []
demo_yr: NA  #not used in Rscript. not sure if we need it
scatter_x: []
scatter_y: []
plot_dir: './'
subtitle: ''
prefix:
baseline_file: ./hfip_baseline.dat
column_info_file: ./plot_tcmpr_hdr.dat
