import pandas as pd
import pytest
import os
from metplotpy.plots.line import line as l

cwd = os.path.dirname(__file__)


def test_custom_line_without_points(module_setup_env, remove_files):
    """Checking that the plot file is getting created but the .points1 and .points2 files are NOT"""
    output_dir = os.environ['TEST_OUTPUT']
    expected_files = ['line.png']
    not_expected_files = ['line.points1', 'line.points2']

    remove_files(os.environ['TEST_OUTPUT'], expected_files + not_expected_files)

    l.main(f"{cwd}/custom_line.yaml")

    for expected_file in expected_files:
        assert os.path.isfile(os.path.join(output_dir, expected_file))

    for not_expected_file in not_expected_files:
        assert not os.path.isfile(os.path.join(output_dir, not_expected_file))


def test_custom_line2_with_points(module_setup_env, remove_files):
    """Checking that the plot and point data files are getting created.
    Checking that no NaNs are found in the pointsN files"""
    output_dir = os.environ['TEST_OUTPUT']
    expected_files = (
        'line.png',
        'intermed_files/line.points1',
        'intermed_files/line.points2'
    )

    remove_files(os.environ['TEST_OUTPUT'], expected_files)

    l.main(f"{cwd}/custom_line2.yaml")

    for expected_file in expected_files:
        assert os.path.isfile(os.path.join(output_dir, expected_file))

    # Check for NaN's in the intermediate files,_line.points1 and line.points2
    # Fail if there are any NaN's-this indicates something went wrong with the
    # line_series.py module's _create_series_points() method.
    with open(f"{output_dir}/intermed_files/line.points1", "r") as f:
        data = f.read()
    assert "NaN" not in data

    with open(f"{output_dir}/intermed_files/line.points2", "r") as f:
        data = f.read()
    assert "NaN" not in data

    # Verify that the nan.points1 file does indeed trigger a "nans_found"
    with open(f"{cwd}/nan.points1", "r") as f:
        data = f.read()
    assert "NaN" in data


def test_custom_line_from_zero(module_setup_env, remove_files):
    """Compare an expected plot with the start_at_zero option, with the
     newly created plot to verify that the plot hasn't changed in appearance."""
    expected_files = [
        'line_from_zero.png'
    ]

    remove_files(os.environ['TEST_OUTPUT'], expected_files)

    l.main(f"{cwd}/custom_line_from_zero.yaml")

    assert(os.path.isfile(f"{os.environ['TEST_OUTPUT']}/line_from_zero.png"))


def test_vertical_plot(module_setup_env, remove_files):
    """Test that the y1 values from the Python version of the vertical plot
     match the y1 values from the METviewer Rplot version of the vertical plot.
     Avoid relying on image comparison tests."""
    expected_files = [
        'vert_line_plot.png',
        'intermed_files/vert_line_plot.points1'
    ]

    remove_files(os.environ['TEST_OUTPUT'], expected_files)

    l.main(f"{cwd}/mv_custom_vert_line.yaml")

    for expected_file in expected_files:
        assert os.path.isfile(os.path.join(os.environ['TEST_OUTPUT'], expected_file))

    output_dir = os.environ['TEST_OUTPUT']

    # Retrieve the .points1 files generated by METviewer and METplotpy respectively
    mv_df = pd.read_csv(f'{cwd}/intermed_files/vert_plot_y1_from_metviewer.points1',
                        sep=" ", header=None)
    mpp_df = pd.read_csv(f'{output_dir}/intermed_files/vert_line_plot.points1', sep=" ",
                         header=None)

    # -----------------------
    # Compare various values
    # -----------------------
    # Verify we are comparing data frames created from the same data
    # Same number of rows:
    assert mv_df.shape[0] == mpp_df.shape[0]
    # Same number of columns:
    assert mv_df.shape[1] == mpp_df.shape[1]

    # Values for each column are the same (accounting for precision between R and
    # Python and
    # different host machines)
    for col in range(mv_df.shape[1]):
        mv_col: pd.Series = mv_df.loc[:, col]
        mpp_col: pd.Series = mpp_df.loc[:, col]
        col_diff: pd.Series = mv_col - mpp_col
        sum_diff: float = abs(col_diff.sum())

        # Allow for differences in arithmetic between machines and differences in
        # R vs Python arithmetic
        # allow difference out to 5th significant figure.
        assert sum_diff < 0.00001


def test_fbias_fixed_vars_vals(module_setup_env, remove_files):
    """Verify that the fixed_vars_vals_input setting reproduces the same data points that METviewer produces."""
    expected_files = (
        'fbias_fixed_vars.png',
        'fbias.points1',
    )

    remove_files(os.environ['TEST_OUTPUT'], expected_files)

    l.main(f"{cwd}/fbias_fixed_vars_vals.yaml")

    for expected_file in expected_files:
        assert os.path.isfile(os.path.join(os.environ['TEST_OUTPUT'], expected_file))

    # Retrieve the .points1 files generated by METviewer and METplotpy respectively
    mv_df = pd.read_csv(f'{cwd}/intermed_files/mv_fixed_var_vals.points1',
                        sep="\t", header=None)
    mpp_df = pd.read_csv(f'{os.environ['TEST_OUTPUT']}/fbias.points1', sep="\t", header=None)

    # Verify that the values in the generated points1 file are identical
    # to those in the METviewer points1 file.

    # First, verify that the points1 files have the same shape
    num_mv_rows = mv_df.shape[0]
    num_mv_cols = mv_df.shape[1]
    num_mpp_rows = mpp_df.shape[0]
    num_mpp_cols = mpp_df.shape[1]

    assert num_mv_rows == num_mpp_rows
    assert num_mv_cols == num_mpp_cols

    # Verify that all of the rows of both have identical values
    for i in range(num_mv_rows):
        assert mv_df.iloc[i][0] == mpp_df.iloc[i][0]


def test_envs_fcst_var_stat(module_setup_env, remove_files):
    """Verify that the environment vars used for fcst_var_val1/2 and stat1/2 in
     a config file creates the same data for plotting as a config file with the
     fcst_var_val1 and stat hard-coded in a config file."""

    expected_files = (
        'env_fcst_var_stat_line.png',
        'intermed_files/env_fcst_var_stat/line.points1',
        'intermed_files/env_fcst_var_stat/line.points2',
    )

    remove_files(os.environ['TEST_OUTPUT'], expected_files)

    os.environ['FCST_VAR_VAL1'] = "RH"
    os.environ['FCST_VAR_STAT1'] = 'MAE'
    os.environ['FCST_VAR_VAL2'] = "TMP"
    os.environ['FCST_VAR_STAT2'] = 'ME'

    l.main(f"{cwd}/env_fcst_var.yaml")

    expected_points1 = f"{cwd}/intermed_files/expected_var_stat_line.points1"
    expected_points2 = f"{cwd}/intermed_files/expected_var_stat_line.points2"
    expected_df1 = pd.read_csv(f'{expected_points1}', sep="\t", header=None)
    expected_df2 = pd.read_csv(f'{expected_points2}', sep="\t", header=None)
    num_expected1_rows = expected_df1.shape[0]
    num_expected1_cols = expected_df1.shape[1]
    num_expected2_rows = expected_df2.shape[0]
    num_expected2_cols = expected_df2.shape[1]

    # Retrieve the .points1 files generated by METplotpy respectively
    mpp_df1 = pd.read_csv(f'{os.environ['TEST_OUTPUT']}/intermed_files/env_fcst_var_stat/line.points1',
                        sep="\t", header=None)
    mpp_df2 = pd.read_csv(f'{os.environ['TEST_OUTPUT']}/intermed_files/env_fcst_var_stat/line.points2', sep="\t", header=None)

    # Verify that the values in the generated points1/2 files are identical
    # to those in the rh_mae_tmp_me_line.points1/2 files.

    # First, verify that the points1 files have the same shape
    num_mpp1_rows = mpp_df1.shape[0]
    num_mpp1_cols = mpp_df1.shape[1]
    num_mpp2_rows = mpp_df2.shape[0]
    num_mpp2_cols = mpp_df2.shape[1]

    assert num_expected1_rows == num_mpp1_rows
    assert num_expected1_cols == num_mpp1_cols
    assert num_expected2_rows == num_mpp2_rows
    assert num_expected2_cols == num_mpp2_cols

    assert mpp_df1.equals(expected_df1)
    assert mpp_df2.equals(expected_df2)
