# This workflow will install Python dependencies, run tests the specified Python version
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python 3.12 tests

on:
  push:
    branches: 
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*    
      - test_*
    paths-ignore:
      - 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
      - '**/LICENSE.md'

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # New job to determine which branches to test
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set-branches.outputs.branches }}
    steps:
      - id: set-branches
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branches=[\"${{ github.head_ref }}\", \"develop\"]" >> $GITHUB_OUTPUT
          else
            echo "branches=[\"${{ github.ref_name }}\"]" >> $GITHUB_OUTPUT
          fi

  build:

    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        branch: ${{ fromJSON(needs.setup-matrix.outputs.branches) }}

    steps:
    # checkout METplotpy
    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}

    # checkout METcalcpy
    - uses: actions/checkout@v4
      with:
        repository: dtcenter/METcalcpy
        path: METcalcpy
        ref: develop

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e METcalcpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --upgrade kaleido

    - name: Test with pytest
      run: |
        export METPLOTPY_TEST_OUTPUT=${{ runner.workspace }}/output/${{ matrix.branch }}
        pytest

    - name: Upload output data artifact
      uses: actions/upload-artifact@v4
      with:
        name: test_output_${{ matrix.branch }}
        path: ${{ runner.workspace }}/output/${{ matrix.branch }}/test_output
