# This workflow will check third-party Python packages for vulnerabilities using two different tools:
# python safety checker and pip-audit.  pip-audit finds vulnerabilities from packages that are dependencies of
# the packages in the requirements.txt file.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python safety check

on:
  push:
    branches:
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*
      - test_*
      - issue_*
  pull_request:
    types: [opened, reopened, synchronize]

env:
  DEP_PATH: ./requirements.txt

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out main
#        uses: actions/checkout@master
#
#      - name: Security vulnerabilities scan
#        uses: aufdenpunkt/python-safety-check@master
#        with: 
#          scan_requirements_file_only: 'true'

  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          python -m venv env/
          source env/bin/activate
          python -m pip install .
      - uses: pypa/gh-action-pip-audit@v1.0.5
        with:
          inputs: requirements.txt
          virtual-environment: env/
          local: true
